#!/usr/bin/env bash
set -euo pipefail

ROOT="${EOS_ROOT:-$HOME/personal/eos}"
keymaps="$ROOT/configs/nvim/lua/config/eos_keymaps.lua"
options="$ROOT/configs/nvim/lua/config/options.lua"
autocmds="$ROOT/configs/nvim/lua/config/autocmds.lua"
loader="$ROOT/configs/nvim/lua/config/keymaps.lua"
plugins="$ROOT/configs/nvim/lua/plugins/eos.lua"
markdown_preview="$ROOT/configs/nvim/lua/config/markdown_preview.lua"
save_plugin="$ROOT/configs/nvim/lua/plugins/save.lua"
wezterm_keys="$ROOT/configs/wezterm/keys.lua"
wezterm_appearance="$ROOT/configs/wezterm/appearance.lua"
wezterm_fonts="$ROOT/configs/wezterm/fonts.lua"
wezterm_events="$ROOT/configs/wezterm/events.lua"
tmux_config="$ROOT/configs/tmux/tmux.conf"

grep -q '"<D-s>", "<cmd>w<cr>"' "$save_plugin"
grep -q 'vim.api.nvim_create_augroup("AutoSave"' "$save_plugin"
grep -q 'vim.api.nvim_buf_call(bufnr' "$save_plugin"
grep -q 'async_write_notebook' "$save_plugin"
grep -q 'vim.system(cmd' "$save_plugin"
grep -q 'request_autosave' "$save_plugin"
if ! grep -q 'path:match("%.ipynb\$")' "$save_plugin"; then
  echo "notebook autosave must use the async jupytext path" >&2
  exit 1
fi

[[ -f "$keymaps" ]] || { echo "missing keymap module: $keymaps"; exit 1; }
[[ -f "$markdown_preview" ]] || { echo "missing Markdown preview module: $markdown_preview"; exit 1; }

grep -q "M.config" "$keymaps"
grep -q "find_files" "$keymaps"
grep -q "<D-k>" "$keymaps"
grep -q "<M-k>" "$keymaps"
grep -q "toggle_explorer" "$keymaps"
grep -q "<leader>f" "$keymaps"
grep -q "clipboard = \"unnamedplus\"" "$keymaps"
grep -q "live_grep" "$keymaps"
grep -q "current_buffer_search" "$keymaps"
grep -q "agent_terminals" "$keymaps"
grep -q "<leader>ac" "$keymaps"
grep -q "<leader>ax" "$keymaps"
grep -q "<leader>ag" "$keymaps"
grep -q "<leader>ae" "$keymaps"
grep -q "claude-work" "$keymaps"
grep -q "codex-work" "$keymaps"
grep -q "claude-personal" "$keymaps"
grep -q "codex-personal" "$keymaps"
grep -q "antigravity-full" "$keymaps"
grep -q "copy_explain_prompt" "$keymaps"
grep -q 'markdown_preview = { "<leader>mp" }' "$keymaps"
grep -q 'require("config.markdown_preview").open' "$keymaps"
grep -q 'vim.fn.termopen({ "glow"' "$markdown_preview"
grep -q 'FileChangedShellPost' "$markdown_preview"
grep -q 'timer:start(1000, 1000' "$markdown_preview"
grep -q 'vim.api.nvim_win_set_cursor' "$markdown_preview"
grep -q 'vim.keymap.set("n", "q"' "$markdown_preview"
grep -q 'vim.api.nvim_win_set_buf(entry.win, entry.source_buf)' "$markdown_preview"
if grep -q 'vim.cmd("tabnew")' "$markdown_preview"; then
  echo "Markdown preview must stay inside the existing window layout" >&2
  exit 1
fi
grep -q "LazyVim/LazyVim" "$plugins"
grep -q "require(\"config.options\")" "$plugins"
grep -q "require(\"config.autocmds\")" "$plugins"
grep -q "require(\"config.eos_keymaps\").setup()" "$plugins"
grep -q "git_review" "$keymaps"
grep -q "gitsigns" "$keymaps"
grep -q "DiffviewOpen" "$keymaps"
grep -q "DiffviewFileHistory %" "$keymaps"
grep -q "<leader>rd" "$keymaps"
grep -q "<leader>rD" "$keymaps"
grep -q "<leader>rp" "$keymaps"
grep -q "<leader>rs" "$keymaps"
grep -q "<leader>rr" "$keymaps"
grep -q "<leader>rS" "$keymaps"
grep -q "<leader>rR" "$keymaps"
grep -q "<leader>rh" "$keymaps"
grep -q "lewis6991/gitsigns.nvim" "$plugins"
grep -q "sindrets/diffview.nvim" "$plugins"
grep -q "require(\"config.eos_keymaps\").setup()" "$loader"
grep -q 'key = "k", mods = "CMD"' "$wezterm_keys"
grep -q 'key = "b", mods = "CMD"' "$wezterm_keys"
grep -q 'key = "b", mods = "CMD|SHIFT"' "$wezterm_keys"
grep -q 'toggle-glare-safe' "$wezterm_keys"
grep -q "glare_safe_colors" "$wezterm_appearance"
grep -q "glare_safe_scheme" "$wezterm_appearance"
grep -q "EOS Glare Safe" "$wezterm_appearance"
grep -q "color_schemes" "$wezterm_appearance"
grep -q "enable_kitty_graphics = true" "$wezterm_appearance"
grep -q 'window_decorations = "TITLE | RESIZE"' "$wezterm_appearance"
grep -q '"JetBrains Mono"' "$wezterm_fonts"
grep -q '"Symbols Nerd Font Mono"' "$wezterm_fonts"
if grep -q 'JetBrainsMono Nerd Font' "$wezterm_appearance" "$wezterm_fonts"; then
  echo "wezterm font config must only reference available font families"
  exit 1
fi
grep -q "background = \"#f4f1e8\"" "$wezterm_appearance"
grep -q "selection_bg" "$wezterm_appearance"
grep -q "toggle-glare-safe" "$wezterm_events"
grep -q "overrides.color_scheme = appearance.glare_safe_scheme" "$wezterm_events"
grep -q "set_config_overrides" "$wezterm_events"
grep -q "Glare Safe on" "$wezterm_events"
grep -q 'key = "s", mods = "CMD"' "$wezterm_keys"
grep -q 'key = "Enter", mods = "SHIFT"' "$wezterm_keys"
grep -q 'key = "w", mods = "CTRL|SHIFT"' "$wezterm_keys"
grep -q 'close-notebook-plot-pane' "$wezterm_keys"
grep -q 'close-notebook-plot-pane' "$wezterm_events"
grep -q 'EOS_NOTEBOOK_PLOTS' "$wezterm_events"
grep -q 'CloseCurrentPane' "$wezterm_events"
grep -Fq '\x1b[13;2u' "$wezterm_keys"
grep -q "xterm-keys on" "$tmux_config"
grep -q "extended-keys on" "$tmux_config"
grep -q "extkeys" "$tmux_config"
grep -q "allow-passthrough on" "$tmux_config"
grep -q "visual-activity off" "$tmux_config"
grep -q "focus-events on" "$tmux_config"
grep -q "vim.opt.swapfile = false" "$options"
grep -q "vim.opt.undofile = true" "$options"
grep -q "vim.opt.autoread = true" "$options"
grep -q "vim.opt.updatetime = 500" "$options"
grep -q "vim.opt.fillchars" "$options"
grep -q "vim.opt.laststatus = 2" "$options"
grep -q "FocusGained" "$autocmds"
grep -q "CursorHold" "$autocmds"
grep -q "CursorHoldI" "$autocmds"
grep -q "checktime" "$autocmds"
grep -q "FileChangedShellPost" "$autocmds"
grep -q "Reloaded from disk" "$autocmds"
grep -q "EosStrongSplit" "$autocmds"
grep -q "nvim_tabpage_list_wins" "$keymaps"
grep -q 'WinSeparator:EosStrongSplit' "$keymaps"
grep -q "EosTerminalWinBar" "$autocmds"
grep -q "EosAgentWinBar" "$autocmds"
grep -q "TermOpen" "$autocmds"
grep -q "vim.opt_local.swapfile = false" "$autocmds"
grep -q "AGENT:" "$keymaps"
grep -q "border = \"rounded\"" "$keymaps"

echo "nvim keymaps ok"
