#!/usr/bin/env bash
set -euo pipefail

ROOT="${EOS_ROOT:-$HOME/personal/eos}"
config="$ROOT/configs/nvim/lua/plugins/notebooks.lua"
brewfile="$ROOT/brew/Brewfile"

[[ -f "$config" ]] || { echo "missing notebook config: $config"; exit 1; }
grep -q '^brew "imagemagick"$' "$brewfile"

grep -q "goerz/jupytext.nvim" "$config"
grep -q "patch_jupytext_notebook_lifecycle" "$config"
grep -q "empty and percent-script notebook recovery" "$config"
grep -q "source_is_percent" "$config"
grep -q "benlubas/molten-nvim" "$config"
grep -q "3rd/image.nvim" "$config"
grep -q 'commit = "bedea63819c618e007e7c40059fc6e72d598c8df"' "$config"
grep -q 'commit = "88351f1f7d9dbae286e671ce3690a49660dd8a5c"' "$config"
grep -q "Vigemus/iron.nvim" "$config"
grep -q "py:percent" "$config"
grep -q "python3_host_prog" "$config"
grep -q ".local/share/eos/notebooks/.venv/bin/python3" "$config"
grep -q ".local/share/eos/notebooks/.venv/bin/ipython" "$config"
grep -q "find_project_venv" "$config"
grep -q "project_kernel_name" "$config"
grep -q "ensure_project_kernel" "$config"
grep -q "notebook_kernel_name" "$config"
grep -q "python_repl_command" "$config"
grep -q "executable_works" "$config"
grep -q "/.venv" "$config"
grep -q "iron.setup" "$config"
grep -q "bracketed_paste_python" "$config"
grep -q "block_dividers" "$config"
grep -q "IronHide python" "$config"
grep -q "IronRestart" "$config"
grep -q "EosNotebookReplWinBar" "$config"
grep -q "PYTHON REPL" "$config"
grep -q "EosNotebookActiveCellHeader" "$config"
grep -q "EosNotebookExecutedCell" "$config"
grep -q "window_for_buffer" "$config"
grep -q "current_cell_marker_line" "$config"
grep -q "notebook_status" "$config"
grep -q "mark_cell_sent(bufnr" "$config"
grep -q "vim.b\\[bufnr\\].eos_notebook_cell_status = status" "$config"
grep -q "Sent" "$config"
grep -q "✔✔" "$config"
grep -q "Cell %d" "$config"
grep -q "NotebookRunCell" "$config"
grep -q "NotebookRunCellInline" "$config"
grep -q "NotebookRunCellRepl" "$config"
grep -q "NotebookRunAll" "$config"
grep -q "NotebookRunAllInline" "$config"
grep -q "NotebookRunAllRepl" "$config"
grep -q "NotebookResetSession" "$config"
grep -q "NotebookInitKernel" "$config"
grep -q "NotebookInterruptKernel" "$config"
grep -q "NotebookExportOutput" "$config"
grep -q "NotebookImportOutput" "$config"
grep -q "NotebookRenderCells" "$config"
grep -q "notebook_keys" "$config"
grep -q "shift_enter_csi_u" "$config"
grep -q "run_cell_advance" "$config"
grep -q "run_cell_inline" "$config"
grep -q "run_all_inline" "$config"
grep -q "run_visual_selection_inline" "$config"
grep -q "molten_init_kernel" "$config"
grep -q "MoltenInit \" .. kernel_name" "$config"
grep -q "molten_image_provider" "$config"
grep -q "eos_molten_image_provider" "$config"
grep -q 'return "wezterm"' "$config"
grep -q 'willothy/wezterm.nvim' "$config"
grep -q 'commit = "032c33b621b96cc7228955b4352b48141c482098"' "$config"
grep -q 'defer WezTerm pane until first image' "$config"
grep -q 'lazy WezTerm image pane' "$config"
grep -q 'recreate closed WezTerm plot pane' "$config"
grep -q 'EOS_NOTEBOOK_PLOTS=MQ==' "$config"
grep -q 'molten_split_direction = "bottom"' "$config"
grep -q 'molten_split_size = 40' "$config"
grep -q 'molten_image_location = "virt"' "$config"
if grep -q 'molten_image_location = "both"' "$config"; then
  echo "notebook image output must use virtual placement only"
  exit 1
fi
grep -q "eos_image_backend" "$config"
grep -q "patch_molten_virtual_output_layout" "$config"
grep -q "apply_plugin_source_patches" "$config"
grep -q 'y = shape\[1\] + lineno + virtual_lines' "$config"
grep -q 'render_offset_top = max(0, lineno - image_y)' "$config"
grep -q '"render_offset_top": render_offset_top' "$config"
grep -q 'previous_cursor = self.display_win.api.get_cursor()' "$config"
grep -q 'row = min(previous_cursor\[0\], len(self.display_buf))' "$config"
grep -q 'nvim_set_current_win(self.display_win.handle)' "$config"
grep -q 'self.nvim.current.buffer.number == self.display_buf.number' "$config"
grep -q 'output.show_floating_win(span.end)' "$config"
grep -q 'output.display_buf.number == current_bufno' "$config"
grep -q 'Output | Run {execution_count}' "$config"
grep -q 'pending_molten_evaluations' "$config"
grep -q 'flush_pending_molten_evaluations' "$config"
grep -q 'pattern = "MoltenKernelReady"' "$config"
grep -q 'vim.b\[bufnr\].eos_molten_ready = false' "$config"
grep -q 'molten_enter_output_behavior = "open_and_enter"' "$config"
grep -q 'image_utils.tmux.has_passthrough = true' "$config"
grep -q 'NotebookOpenOutput' "$config"
grep -q 'pattern = "molten_output"' "$config"
grep -q 'MoltenOutputHeader' "$config"
grep -q 'line.ljust(max(1, shape\[2\]))' "$config"
grep -Fq '[(" " * max(1, shape[2]), "MoltenOutputFooter")]' "$config"
grep -q 'bg = "#155e75"' "$config"
grep -q "molten_cover_empty_lines = false" "$config"
grep -q "molten_output_virt_lines = false" "$config"
grep -q "molten_virt_lines_off_by_1 = false" "$config"
if grep -q "molten_virt_lines_off_by_1 = true" "$config"; then
  echo "percent-cell output must stay anchored below the evaluated cell"
  exit 1
fi
grep -q "max_width = 100" "$config"
grep -q "max_height = 24" "$config"
grep -q "max_width_window_percentage = math.huge" "$config"
grep -q "max_height_window_percentage = math.huge" "$config"
grep -q 'return "kitty"' "$config"
grep -q 'return "sixel"' "$config"
grep -q 'patch_image_nvim_sixel_backend' "$config"
grep -q 'patch_image_nvim_sixel_backend(plugin)' "$config"
grep -q 'local FLUSH_DELAY_MS = 120' "$config"
grep -q 'local stdout = vim.uv.new_tty(1, false)' "$config"
grep -q 'stdout:write(sequence)' "$config"
grep -q "native tmux SIXEL transport" "$config"
grep -q 'window_overlap_clear_enabled = false' "$config"
grep -q "reset_session" "$config"
grep -q "reset_python_session" "$config"
grep -q "Register work before MoltenInit" "$config"
grep -q "<S-CR>" "$config"
grep -Fq '\27[13;2u' "$config"
grep -q "EosNotebookCellHeader" "$config"
grep -q "EosNotebookCodeCell" "$config"
grep -q "EosNotebookMarkdownCell" "$config"
grep -q "EosNotebookRunCell" "$config"
grep -q "EosNotebookMuted" "$config"
grep -q "MoltenVirtualText" "$config"
grep -q "MoltenOutputBorderSuccess" "$config"
grep -q 'molten_output_win_border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" }' "$config"
grep -q "virt_text_pos = \"overlay\"" "$config"
grep -q "signcolumn = \"yes:2\"" "$config"
grep -q 'is_active and ">>"' "$config"
grep -q "go_to_next_cell" "$config"
grep -q "go_to_previous_cell" "$config"
grep -q "render_cell_markers" "$config"
grep -q "insert_code_cell" "$config"
grep -q "insert_markdown_cell" "$config"
grep -q "clear_cell_status" "$config"
grep -q "<leader>jR" "$config"
grep -q "<leader>jc" "$config"
grep -q "<leader>jm" "$config"
grep -q "<leader>jx" "$config"
grep -q "<leader>jf" "$config"
grep -q "<leader>jI" "$config"
grep -q "<leader>je" "$config"
grep -q "<leader>jE" "$config"

grep -q "ipython" "$ROOT/scripts/setup-notebooks"
grep -q "matplotlib" "$ROOT/scripts/setup-notebooks"
grep -q "numpy" "$ROOT/scripts/setup-notebooks"
grep -q "jupyter_client" "$ROOT/scripts/setup-notebooks"
grep -q "nbformat" "$ROOT/scripts/setup-notebooks"

jupytext_source="$HOME/.local/share/nvim/lazy/jupytext.nvim/lua/jupytext.lua"
grep -q 'source_is_percent' "$jupytext_source"
grep -q "raw_content:match('^%s\*\$')" "$jupytext_source"
grep -q "if source_content:match('^%s\*{') then" "$jupytext_source"
grep -q "local destination_is_json = false" "$jupytext_source"

molten_source="$HOME/.local/share/nvim/lazy/molten-nvim/rplugin/python3/molten/outputbuffer.py"
molten_chunks="$HOME/.local/share/nvim/lazy/molten-nvim/rplugin/python3/molten/outputchunks.py"
molten_images="$HOME/.local/share/nvim/lazy/molten-nvim/rplugin/python3/molten/images.py"
molten_buffer="$HOME/.local/share/nvim/lazy/molten-nvim/rplugin/python3/molten/moltenbuffer.py"
molten_init="$HOME/.local/share/nvim/lazy/molten-nvim/rplugin/python3/molten/__init__.py"
[[ -f "$molten_source" ]] || { echo "installed Molten source is missing: $molten_source"; exit 1; }
[[ -f "$molten_chunks" ]] || { echo "installed Molten output chunks are missing: $molten_chunks"; exit 1; }
[[ -f "$molten_images" ]] || { echo "installed Molten image canvas is missing: $molten_images"; exit 1; }
[[ -f "$molten_buffer" ]] || { echo "installed Molten buffer is missing: $molten_buffer"; exit 1; }
[[ -f "$molten_init" ]] || { echo "installed Molten entrypoint is missing: $molten_init"; exit 1; }
grep -q 'Output | Run {execution_count}' "$molten_source"
grep -q 'MoltenOutputHeader' "$molten_source"
grep -q 'MoltenOutputFooter' "$molten_source"
grep -q 'line.ljust(max(1, shape\[2\]))' "$molten_source"
grep -q 'y = shape\[1\] + lineno + virtual_lines' "$molten_source"
grep -q 'previous_cursor = self.display_win.api.get_cursor()' "$molten_source"
grep -q 'row = min(previous_cursor\[0\], len(self.display_buf))' "$molten_source"
grep -q 'nvim_set_current_win(self.display_win.handle)' "$molten_source"
grep -q 'EOS opens the WezTerm plot pane lazily when an image is emitted' "$molten_init"
grep -q 'self.image_pane = self.wezterm_api.send_image' "$molten_images"
if grep -q 'nvim_set_current_win(self.display_win)$' "$molten_source"; then
  echo "installed Molten output entry passes a Window object instead of its handle"
  exit 1
fi
grep -q 'self.nvim.current.buffer.number == self.display_buf.number' "$molten_source"
grep -q 'render_offset_top = max(0, lineno - image_y)' "$molten_chunks"
grep -q '"render_offset_top": render_offset_top' "$molten_images"
grep -q 'output.show_floating_win(span.end)' "$molten_buffer"
grep -q 'output.display_buf.number == current_bufno' "$molten_init"
if grep -q 'Out\[{execution_count}\]' "$molten_source"; then
  echo "installed Molten output labels still look like EOS cell numbers"
  exit 1
fi
PYTHONPYCACHEPREFIX="${TMPDIR:-/tmp}/eos-notebook-pycache" \
  "$HOME/.local/share/eos/notebooks/.venv/bin/python3" -m py_compile "$molten_source" "$molten_chunks" "$molten_images" "$molten_buffer" "$molten_init"

molten_wezterm_loader="$HOME/.local/share/nvim/lazy/molten-nvim/lua/load_wezterm_nvim.lua"
grep -q 'EOS_NOTEBOOK_PLOTS=MQ==' "$molten_wezterm_loader"
grep -q 'wezterm.list_panes()' "$molten_wezterm_loader"
grep -q 'return image_pane_id' "$molten_wezterm_loader"

echo "nvim notebook config ok"
