#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export EOS_ROOT="$ROOT"
branching_skill="$ROOT/configs/agents/skills/branching-discussion/SKILL.md"

[[ -x "$ROOT/scripts/render-agent-instructions" ]]
"$ROOT/scripts/render-agent-instructions"
"$ROOT/scripts/render-agent-instructions" --check

for adapter in AGENTS.md CLAUDE.md GEMINI.md; do
  file="$ROOT/configs/agents/$adapter"
  grep -q '^<!-- generated by scripts/render-agent-instructions; do not edit -->$' "$file"
  grep -q '^source: fragments/critical-rules.md sha256:' "$file"
  grep -q '^source: fragments/global-context.md sha256:' "$file"
  grep -q '^source: common-knowledge.md sha256:' "$file"
  # Every skill on disk must be rendered into every adapter, so the skills
  # directory and the generated instructions can never drift apart.
  while IFS= read -r skill_path; do
    grep -q "$skill_path" "$file"
    skill_file="$ROOT/$skill_path"
    skill_description="$(sed -n 's/^description: //p' "$skill_file" | head -1)"
    [[ -n "$skill_description" ]]
    grep -Fq "$skill_description" "$file"
  done < <(find "$ROOT/configs/agents/skills" -mindepth 2 -maxdepth 2 -name SKILL.md \
    | sed "s#^$ROOT/##" | LC_ALL=C sort)
  grep -q 'shared knowledge bases' "$file"
done

grep -q "wait for the user's confirmation before popping the return stack" "$branching_skill"
grep -q "Keep turns short and conversational" "$branching_skill"
grep -q "Make branching audible" "$branching_skill"
grep -q "Mandatory for any open-ended discussion" "$branching_skill"
grep -q 'Every discussion, across every repository and work/personal profile' "$ROOT/configs/agents/fragments/global-context.md"

critical="$ROOT/configs/agents/fragments/critical-rules.md"
[[ "$(wc -l < "$critical")" -le 20 ]]
grep -q 'Always use simple, direct language' "$critical"
grep -q 'reading its `SKILL.md` completely and following it is mandatory' "$critical"
! LC_ALL=C grep -q "$(printf '\342\200\224')" "$ROOT/configs/agents"/*.md "$ROOT/configs/agents"/fragments/*.md
! rg -n '[\x{0900}-\x{097F}]' "$ROOT/configs/agents" --glob '*.md'
echo "agent policy render ok"
