alias ll='eza -la --icons --git'
alias lt='eza --tree --level=2 --icons'
alias cat='bat'
alias lg='lazygit'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gpl='git pull'
alias v='nvim'
alias c='clear'

alias waitwhiz_staging='ssh -i ~/.keys/waitwhiz-staging.pem ubuntu@ec2-65-2-46-206.ap-south-1.compute.amazonaws.com'
alias waitwhiz_prod='ssh -i ~/.keys/main-server-key.pem ubuntu@ec2-15-207-242-192.ap-south-1.compute.amazonaws.com'
alias waitwhiz_sip_prod='ssh -i ~/.keys/main-server-key.pem ubuntu@ec2-52-66-77-15.ap-south-1.compute.amazonaws.com'
